[package]
name = "fenix-gui"
version.workspace = true
edition.workspace = true

[[bin]]
name = "fenix"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.104"
arboard = "3"
bytemuck = { version = "1.25.2", features = ["derive"] }
chrono = "0.4"
dirs = "6"
fenix-buffers = { path = "../fenix-buffers" }
fenix-completion = { path = "../fenix-completion" }
fenix-config = { path = "../fenix-config" }
fenix-core = { path = "../fenix-core" }
fenix-docker = { path = "../fenix-docker" }
fenix-explorer = { path = "../fenix-explorer" }
fenix-format = { path = "../fenix-format" }
fenix-git = { path = "../fenix-git" }
fenix-jira = { path = "../fenix-jira" }
fenix-keymap = { path = "../fenix-keymap" }
fenix-lsp = { path = "../fenix-lsp" }
fenix-mib = { path = "../fenix-mib" }
fenix-pdf = { path = "../fenix-pdf" }
fenix-picker = { path = "../fenix-picker" }
fenix-project = { path = "../fenix-project" }
fenix-syntax = { path = "../fenix-syntax" }
fenix-table = { path = "../fenix-table" }
fenix-terminal = { path = "../fenix-terminal" }
fenix-vim = { path = "../fenix-vim" }
fenix-vnc = { path = "../fenix-vnc" }
fenix-window = { path = "../fenix-window" }
glyphon = "0.12.0"
image = { version = "0.25", default-features = false, features = ["ico", "png"] }
lsp-types = "0.97"
pollster = "1.0.1"
serde_json = "1"
vt100 = "0.16"
wgpu = "30.0.1"
winit = "0.30.13"

[build-dependencies]
winresource = "0.1"
