[package]
name = "fenix-gui"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.104"
bytemuck = { version = "1.25.2", features = ["derive"] }
chrono = "0.4"
dirs = "6"
fenix-buffers = { path = "../fenix-buffers" }
fenix-completion = { path = "../fenix-completion" }
fenix-config = { path = "../fenix-config" }
fenix-core = { path = "../fenix-core" }
fenix-docker = { path = "../fenix-docker" }
fenix-explorer = { path = "../fenix-explorer" }
fenix-git = { path = "../fenix-git" }
fenix-keymap = { path = "../fenix-keymap" }
fenix-picker = { path = "../fenix-picker" }
fenix-project = { path = "../fenix-project" }
fenix-syntax = { path = "../fenix-syntax" }
fenix-vim = { path = "../fenix-vim" }
fenix-window = { path = "../fenix-window" }
glyphon = "0.12.0"
pollster = "1.0.1"
wgpu = "30.0.1"
winit = "0.30.13"
