[package]
name = "fenix-syntax"
version.workspace = true
edition.workspace = true

[dependencies]
tree-sitter = "0.25"
tree-sitter-rust = "0.24"
tree-sitter-toml-ng = "0.7"
tree-sitter-md = "0.5"
tree-sitter-json = "0.24"
tree-sitter-yaml = "0.7"
tree-sitter-python = "0.25"
tree-sitter-javascript = "0.25"
tree-sitter-typescript = "0.23"
tree-sitter-c = "0.24"
tree-sitter-bash = "0.25"
tree-sitter-tcl = { git = "https://github.com/tree-sitter-grammars/tree-sitter-tcl", rev = "850a72ab6436e06645b33b11cfa60cbdb04b1f01" }
