[package]
name = "fenix-project"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
fenix-storage = { path = "../fenix-storage" }
dirs = "6"
fenix-mib = { path = "../fenix-mib" }
fenix-picker = { path = "../fenix-picker" }

serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "1"

[dev-dependencies]
tempfile = "3"
