//! Files generated from a MIB for other tools: XTCE (CCSDS 660.0-B) for
//! XTCE-based ground systems, a Wireshark Lua dissector, a C header, a
//! Python module, an ICD in Markdown, and TC test vectors. Each says at
//! its top what it was generated from, so it can be regenerated and the
//! difference reviewed.

use fenix_ccsds::pus::Profile;

use crate::detail::{self, CalBody};
use crate::packets::{self, OffsetBase};
use crate::set::{CalKind, DefRef, Kind, MibSet};
use crate::types::{self, parse_int};

/// What each generator is called, its file name, and what it makes.
pub const KINDS: &[(&str, &str, &str)] = &[
    ("xtce", "xtce.xml", "XTCE (CCSDS 660.0-B) for XTCE-based ground systems"),
    ("wireshark", "mib_dissector.lua", "a Wireshark dissector: packets by SPID"),
    ("c", "mib.h", "a C header: APIDs, SPIDs, status values, parameter positions"),
    ("python", "mib.py", "a Python module: encode telecommands, decode packets"),
    ("icd", "icd.md", "an ICD in Markdown: every telecommand and packet"),
    ("vectors", "tc_vectors.txt", "every telecommand with its defaults, as hex"),
];

fn stamp(set: &MibSet, comment: &str) -> String {
    let roots: Vec<String> = (0..set.roots().len())
        .map(|i| {
            let info = set.root_info(i);
            format!("{}{}", set.root_label(i), info.version.map(|v| format!(" ({v})")).unwrap_or_default())
        })
        .collect();
    format!("{comment} Generated by Fenix from the MIB {} -- regenerate rather than edit.\n", roots.join(", "))
}

fn xml(s: &str) -> String {
    s.replace('&', "&amp;").replace('<', "&lt;").replace('>', "&gt;").replace('"', "&quot;")
}

/// A name safe as an identifier in C, Python and Lua.
fn ident(s: &str) -> String {
    let mut out: String = s.chars().map(|c| if c.is_ascii_alphanumeric() { c } else { '_' }).collect();
    if out.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        out.insert(0, '_');
    }
    out
}

/// Where a TM parameter sits in a packet, in bits from the packet's start.
struct Placed {
    name: String,
    bit: usize,
    bits: usize,
    ptc: String,
}

fn placed(set: &MibSet, spid: DefRef, profile: &Profile, base: OffsetBase) -> Vec<Placed> {
    let head = packets::params_start(set, spid, profile, base);
    detail::packet_slots(set, spid)
        .into_iter()
        .filter_map(|s| {
            let p = set.get(s.param?);
            let t = types::decode(p.row.clean("PCF_PTC"), p.row.clean("PCF_PFC"));
            Some(Placed { name: s.name, bit: (head + s.byte.unwrap_or(0).max(0) as usize) * 8 + s.bit.unwrap_or(0).max(0) as usize, bits: t.bits? as usize, ptc: p.row.clean("PCF_PTC").to_string() })
        })
        .collect()
}

fn xtce_type(ptc: &str, pfc: &str, name: &str, unit: &str, cal: Option<(DefRef, &MibSet)>, arg: bool) -> String {
    let t = types::decode(ptc, pfc);
    let bits = t.bits.unwrap_or(8);
    let kind = if arg { "Argument" } else { "Parameter" };
    let units = if unit.is_empty() { String::new() } else { format!("<xtce:UnitSet><xtce:Unit>{}</xtce:Unit></xtce:UnitSet>", xml(unit)) };
    let enc_int = |signed: bool| format!("<xtce:IntegerDataEncoding sizeInBits=\"{bits}\" encoding=\"{}\"/>", if signed { "twosComplement" } else { "unsigned" });
    if let Some((c, set)) = cal {
        match detail::calibration(set, c) {
            CalBody::Texts(texts) => {
                let list: String = texts
                    .iter()
                    .filter_map(|(raw, text)| {
                        let (lo, hi) = raw.split_once("..").unwrap_or((raw, raw));
                        let (lo, hi) = (parse_int(lo)?, parse_int(hi)?);
                        Some(if lo == hi { format!("<xtce:Enumeration value=\"{lo}\" label=\"{}\"/>", xml(text)) } else { format!("<xtce:Enumeration value=\"{lo}\" maxValue=\"{hi}\" label=\"{}\"/>", xml(text)) })
                    })
                    .collect();
                return format!("<xtce:Enumerated{kind}Type name=\"{name}\">{units}{}<xtce:EnumerationList>{list}</xtce:EnumerationList></xtce:Enumerated{kind}Type>", enc_int(false));
            }
            CalBody::Points(points) if !arg => {
                let pts: String = points.iter().map(|(r, e)| format!("<xtce:SplinePoint raw=\"{}\" calibrated=\"{}\"/>", xml(r), xml(e))).collect();
                return format!(
                    "<xtce:Float{kind}Type name=\"{name}\">{units}{}<xtce:DefaultCalibrator><xtce:SplineCalibrator>{pts}</xtce:SplineCalibrator></xtce:DefaultCalibrator></xtce:IntegerDataEncoding></xtce:Float{kind}Type>",
                    enc_int(false).trim_end_matches("/>").to_string() + ">"
                );
            }
            CalBody::Coefficients(k) if !arg => {
                let terms: String = k.iter().enumerate().map(|(i, c)| format!("<xtce:Term coefficient=\"{}\" exponent=\"{i}\"/>", xml(c))).collect();
                return format!(
                    "<xtce:Float{kind}Type name=\"{name}\">{units}{}<xtce:DefaultCalibrator><xtce:PolynomialCalibrator>{terms}</xtce:PolynomialCalibrator></xtce:DefaultCalibrator></xtce:IntegerDataEncoding></xtce:Float{kind}Type>",
                    enc_int(false).trim_end_matches("/>").to_string() + ">"
                );
            }
            _ => {}
        }
    }
    match ptc.trim() {
        "1" => format!("<xtce:Boolean{kind}Type name=\"{name}\">{units}{}</xtce:Boolean{kind}Type>", enc_int(false)),
        "5" => format!("<xtce:Float{kind}Type name=\"{name}\" sizeInBits=\"{bits}\">{units}<xtce:FloatDataEncoding sizeInBits=\"{bits}\"/></xtce:Float{kind}Type>"),
        "8" => format!("<xtce:String{kind}Type name=\"{name}\">{units}<xtce:StringDataEncoding><xtce:SizeInBits><xtce:Fixed><xtce:FixedValue>{bits}</xtce:FixedValue></xtce:Fixed></xtce:SizeInBits></xtce:StringDataEncoding></xtce:String{kind}Type>"),
        "4" => format!("<xtce:Integer{kind}Type name=\"{name}\" signed=\"true\" sizeInBits=\"{bits}\">{units}{}</xtce:Integer{kind}Type>", enc_int(true)),
        _ => format!("<xtce:Integer{kind}Type name=\"{name}\" signed=\"false\" sizeInBits=\"{bits}\">{units}{}</xtce:Integer{kind}Type>", enc_int(false)),
    }
}

/// XTCE for every definition: parameters with their types and
/// calibrations, a packet container per SPID restricted by APID, service
/// and subtype, a meta-command per telecommand.
pub fn xtce(set: &MibSet, profile: &Profile, base: OffsetBase) -> String {
    let mut out = String::from("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
    // XML comments can't hold "--".
    out.push_str(&format!("<!-- {} -->\n", stamp(set, "").trim().replace("--", ";")));
    out.push_str("<xtce:SpaceSystem xmlns:xtce=\"http://www.omg.org/spec/XTCE/20180204\" name=\"MIB\">\n");
    // Telemetry.
    out.push_str("  <xtce:TelemetryMetaData>\n    <xtce:ParameterTypeSet>\n");
    for h in [("CCSDS_APID", 11), ("PUS_SERVICE", 8), ("PUS_SUBTYPE", 8)] {
        out.push_str(&format!("      <xtce:IntegerParameterType name=\"{}_type\" signed=\"false\" sizeInBits=\"{}\"><xtce:IntegerDataEncoding sizeInBits=\"{}\"/></xtce:IntegerParameterType>\n", h.0, h.1, h.1));
    }
    for (i, e) in set.entries(Kind::TmParam).iter().enumerate() {
        let def = DefRef { kind: Kind::TmParam, index: i };
        let cal = detail::tm_calibration(set, def).map(|c| (c, set));
        out.push_str(&format!("      {}\n", xtce_type(e.row.clean("PCF_PTC"), e.row.clean("PCF_PFC"), &format!("{}_type", xml(&e.name)), e.row.clean("PCF_UNIT"), cal, false)));
    }
    out.push_str("    </xtce:ParameterTypeSet>\n    <xtce:ParameterSet>\n");
    for h in ["CCSDS_APID", "PUS_SERVICE", "PUS_SUBTYPE"] {
        out.push_str(&format!("      <xtce:Parameter name=\"{h}\" parameterTypeRef=\"{h}_type\"/>\n"));
    }
    for e in set.entries(Kind::TmParam) {
        out.push_str(&format!("      <xtce:Parameter name=\"{}\" parameterTypeRef=\"{}_type\"><xtce:LongDescription>{}</xtce:LongDescription></xtce:Parameter>\n", xml(&e.name), xml(&e.name), xml(&e.description)));
    }
    out.push_str("    </xtce:ParameterSet>\n    <xtce:ContainerSet>\n");
    out.push_str("      <xtce:SequenceContainer name=\"CCSDS_Packet\" abstract=\"true\"><xtce:EntryList>");
    out.push_str("<xtce:ParameterRefEntry parameterRef=\"CCSDS_APID\"><xtce:LocationInContainerInBits referenceLocation=\"containerStart\"><xtce:FixedValue>5</xtce:FixedValue></xtce:LocationInContainerInBits></xtce:ParameterRefEntry>");
    out.push_str("<xtce:ParameterRefEntry parameterRef=\"PUS_SERVICE\"><xtce:LocationInContainerInBits referenceLocation=\"containerStart\"><xtce:FixedValue>56</xtce:FixedValue></xtce:LocationInContainerInBits></xtce:ParameterRefEntry>");
    out.push_str("<xtce:ParameterRefEntry parameterRef=\"PUS_SUBTYPE\"><xtce:LocationInContainerInBits referenceLocation=\"containerStart\"><xtce:FixedValue>64</xtce:FixedValue></xtce:LocationInContainerInBits></xtce:ParameterRefEntry>");
    out.push_str("</xtce:EntryList></xtce:SequenceContainer>\n");
    for (i, e) in set.entries(Kind::TmPacket).iter().enumerate() {
        let spid = DefRef { kind: Kind::TmPacket, index: i };
        let r = &e.row;
        let name = if e.alias.is_empty() { format!("SPID_{}", e.name) } else { ident(&e.alias) };
        out.push_str(&format!("      <xtce:SequenceContainer name=\"{}\" shortDescription=\"SPID {}\"><xtce:LongDescription>{}</xtce:LongDescription><xtce:EntryList>", xml(&name), xml(&e.name), xml(&e.description)));
        for p in placed(set, spid, profile, base) {
            out.push_str(&format!(
                "<xtce:ParameterRefEntry parameterRef=\"{}\"><xtce:LocationInContainerInBits referenceLocation=\"containerStart\"><xtce:FixedValue>{}</xtce:FixedValue></xtce:LocationInContainerInBits></xtce:ParameterRefEntry>",
                xml(&p.name),
                p.bit
            ));
        }
        out.push_str(&format!(
            "</xtce:EntryList><xtce:BaseContainer containerRef=\"CCSDS_Packet\"><xtce:RestrictionCriteria><xtce:ComparisonList><xtce:Comparison parameterRef=\"CCSDS_APID\" value=\"{}\"/><xtce:Comparison parameterRef=\"PUS_SERVICE\" value=\"{}\"/><xtce:Comparison parameterRef=\"PUS_SUBTYPE\" value=\"{}\"/></xtce:ComparisonList></xtce:RestrictionCriteria></xtce:BaseContainer></xtce:SequenceContainer>\n",
            parse_int(r.clean("PID_APID")).unwrap_or(0),
            parse_int(r.clean("PID_TYPE")).unwrap_or(0),
            parse_int(r.clean("PID_STYPE")).unwrap_or(0)
        ));
    }
    out.push_str("    </xtce:ContainerSet>\n  </xtce:TelemetryMetaData>\n");
    // Commands.
    out.push_str("  <xtce:CommandMetaData>\n    <xtce:ArgumentTypeSet>\n");
    for (i, e) in set.entries(Kind::TcParam).iter().enumerate() {
        let def = DefRef { kind: Kind::TcParam, index: i };
        let cal = detail::tc_param_calibrations(set, def).into_iter().find(|c| set.get(*c).cal == Some(CalKind::Status)).map(|c| (c, set));
        out.push_str(&format!("      {}\n", xtce_type(e.row.clean("CPC_PTC"), e.row.clean("CPC_PFC"), &format!("{}_type", xml(&e.name)), e.row.clean("CPC_UNIT"), cal, true)));
    }
    out.push_str("    </xtce:ArgumentTypeSet>\n    <xtce:MetaCommandSet>\n");
    for (i, e) in set.entries(Kind::Telecommand).iter().enumerate() {
        let tc = DefRef { kind: Kind::Telecommand, index: i };
        let r = &e.row;
        out.push_str(&format!(
            "      <xtce:MetaCommand name=\"{}\" shortDescription=\"{}\"><xtce:LongDescription>{}</xtce:LongDescription><xtce:AncillaryDataSet><xtce:AncillaryData name=\"APID\">{}</xtce:AncillaryData><xtce:AncillaryData name=\"TYPE\">{}</xtce:AncillaryData><xtce:AncillaryData name=\"SUBTYPE\">{}</xtce:AncillaryData><xtce:AncillaryData name=\"ACK\">{}</xtce:AncillaryData></xtce:AncillaryDataSet><xtce:ArgumentList>",
            xml(&e.name),
            xml(&e.description),
            xml(r.clean("CCF_DESCR2")),
            r.clean("CCF_APID"),
            r.clean("CCF_TYPE"),
            r.clean("CCF_STYPE"),
            r.clean("CCF_ACK")
        ));
        let els = detail::tc_elements(set, tc);
        for el in els.iter().filter(|el| el.fixed.is_none() && !el.name.is_empty()) {
            let initial = if el.default.is_empty() { String::new() } else { format!(" initialValue=\"{}\"", xml(&el.default)) };
            out.push_str(&format!("<xtce:Argument name=\"{}\" argumentTypeRef=\"{}_type\"{initial}/>", xml(&el.name), xml(&el.name)));
        }
        out.push_str(&format!("</xtce:ArgumentList><xtce:CommandContainer name=\"{}_container\"><xtce:EntryList>", xml(&e.name)));
        for el in &els {
            let (Some(bit), Some(bits)) = (el.bit, el.bits) else { continue };
            let loc = format!("<xtce:LocationInContainerInBits referenceLocation=\"containerStart\"><xtce:FixedValue>{bit}</xtce:FixedValue></xtce:LocationInContainerInBits>");
            match &el.fixed {
                Some(v) => out.push_str(&format!("<xtce:FixedValueEntry name=\"{}\" binaryValue=\"{:0w$X}\" sizeInBits=\"{bits}\">{loc}</xtce:FixedValueEntry>", xml(if el.name.is_empty() { "spare" } else { &el.name }), parse_int(v).unwrap_or(0), w = (bits as usize).div_ceil(4).max(1))),
                None if el.name.is_empty() => out.push_str(&format!("<xtce:FixedValueEntry name=\"spare\" binaryValue=\"0\" sizeInBits=\"{bits}\">{loc}</xtce:FixedValueEntry>")),
                None => out.push_str(&format!("<xtce:ArgumentRefEntry argumentRef=\"{}\">{loc}</xtce:ArgumentRefEntry>", xml(&el.name))),
            }
        }
        out.push_str("</xtce:EntryList></xtce:CommandContainer></xtce:MetaCommand>\n");
    }
    out.push_str("    </xtce:MetaCommandSet>\n  </xtce:CommandMetaData>\n</xtce:SpaceSystem>\n");
    out
}

/// The PIC checks that tell TM packet `row` from others with its APID,
/// type and subtype: (bit from the packet's start, bits, value) for PI1
/// and PI2, as `packets::identify_tm` reads them.
fn pi_checks(set: &MibSet, row: &crate::Row) -> Vec<(i64, i64, i64)> {
    let (service, subtype, apid) = (parse_int(row.clean("PID_TYPE")), parse_int(row.clean("PID_STYPE")), parse_int(row.clean("PID_APID")));
    let Some(pic) = set.index().rows("pic").iter().find(|r| {
        parse_int(r.clean("PIC_TYPE")) == service
            && parse_int(r.clean("PIC_STYPE")) == subtype
            && r.get("PIC_APID").map(str::trim).filter(|a| !a.is_empty()).is_none_or(|a| parse_int(a) == apid)
    }) else {
        return Vec::new();
    };
    [("PIC_PI1_OFF", "PIC_PI1_WID", "PID_PI1_VAL"), ("PIC_PI2_OFF", "PIC_PI2_WID", "PID_PI2_VAL")]
        .iter()
        .filter_map(|(off, wid, val)| {
            let (off, wid) = (parse_int(pic.clean(off))?, parse_int(pic.clean(wid))?);
            (off >= 0 && wid > 0).then(|| (off * 8, wid, parse_int(row.clean(val)).unwrap_or(0)))
        })
        .collect()
}

/// A Wireshark Lua dissector: the space packet and PUS-C headers, then
/// each packet's parameters by SPID, for packets carried over UDP.
pub fn wireshark(set: &MibSet, profile: &Profile, base: OffsetBase) -> String {
    let mut out = stamp(set, "--");
    out.push_str("-- Load with: wireshark -X lua_script:mib_dissector.lua ; packets on UDP port 10015 (Decode As... for others).\n");
    out.push_str("local p = Proto(\"mib\", \"CCSDS packet (MIB)\")\nlocal f = p.fields\n");
    out.push_str("f.apid = ProtoField.uint16(\"mib.apid\", \"APID\", base.HEX, nil, 0x07FF)\nf.type = ProtoField.uint8(\"mib.type\", \"Packet type\", base.DEC, {[0]=\"TM\",[1]=\"TC\"})\nf.seq = ProtoField.uint16(\"mib.seq\", \"Sequence count\", base.DEC, nil, 0x3FFF)\nf.len = ProtoField.uint16(\"mib.length\", \"Data length\")\nf.svc = ProtoField.uint8(\"mib.service\", \"Service\")\nf.sub = ProtoField.uint8(\"mib.subtype\", \"Subtype\")\nf.spid = ProtoField.string(\"mib.spid\", \"SPID\")\n");
    out.push_str("local params = {}\n");
    let mut seen = std::collections::HashSet::new();
    for e in set.entries(Kind::TmParam) {
        if seen.insert(e.name.clone()) {
            out.push_str(&format!("params[\"{0}\"] = ProtoField.uint64(\"mib.p.{0}\", \"{0} {1}\")\nf[\"p_{0}\"] = params[\"{0}\"]\n", ident(&e.name), e.description.replace('"', "'")));
        }
    }
    out.push_str("-- { apid, service, subtype, { {bit, bits, value} checks of PI1/PI2 }, name, { {param, bit, bits}, ... } }\nlocal packets = {\n");
    for (i, e) in set.entries(Kind::TmPacket).iter().enumerate() {
        let spid = DefRef { kind: Kind::TmPacket, index: i };
        let r = &e.row;
        let ps: Vec<String> = placed(set, spid, profile, base).into_iter().filter(|p| p.bits <= 64 && p.ptc != "8").map(|p| format!("{{\"{}\", {}, {}}}", ident(&p.name), p.bit, p.bits)).collect();
        let pis: Vec<String> = pi_checks(set, r).iter().map(|(b, n, v)| format!("{{{b}, {n}, {v}}}")).collect();
        out.push_str(&format!(
            "  {{ {}, {}, {}, {{ {} }}, \"{} {}\", {{ {} }} }},\n",
            parse_int(r.clean("PID_APID")).unwrap_or(0),
            parse_int(r.clean("PID_TYPE")).unwrap_or(0),
            parse_int(r.clean("PID_STYPE")).unwrap_or(0),
            pis.join(", "),
            e.name,
            e.alias,
            ps.join(", ")
        ));
    }
    out.push_str("}\n");
    out.push_str(
        r#"local function bits(tvb, at, n)
  local v = UInt64(0)
  for i = at, at + n - 1 do
    local byte = tvb(math.floor(i / 8), 1):uint()
    local b = bit.band(bit.rshift(byte, 7 - (i % 8)), 1)
    v = v * 2 + b
  end
  return v
end

function p.dissector(tvb, pinfo, tree)
  if tvb:len() < 6 then return end
  pinfo.cols.protocol = "MIB"
  local t = tree:add(p, tvb())
  local word = tvb(0, 2):uint()
  local apid = bit.band(word, 0x7FF)
  local is_tc = bit.band(bit.rshift(word, 12), 1)
  t:add(f.type, tvb(0, 1), is_tc)
  t:add(f.apid, tvb(0, 2))
  t:add(f.seq, tvb(2, 2))
  t:add(f.len, tvb(4, 2))
  if tvb:len() < 9 then return end
  local svc, sub = tvb(7, 1):uint(), tvb(8, 1):uint()
  t:add(f.svc, tvb(7, 1))
  t:add(f.sub, tvb(8, 1))
  local def = nil
  for _, d in ipairs(packets) do
    if def == nil and d[1] == apid and d[2] == svc and d[3] == sub then
      local ok = true
      for _, c in ipairs(d[4]) do
        if (c[1] + c[2]) > tvb:len() * 8 or bits(tvb, c[1], c[2]) ~= UInt64(c[3]) then ok = false end
      end
      if ok then def = d end
    end
  end
  if def == nil then return end
  t:add(f.spid, def[5])
  pinfo.cols.info = def[5]
  for _, e in ipairs(def[6]) do
    local at, n = e[2], e[3]
    if (at + n) <= tvb:len() * 8 then
      t:add(params[e[1]], tvb(math.floor(at / 8), math.ceil(n / 8)), bits(tvb, at, n))
    end
  end
end

DissectorTable.get("udp.port"):add(10015, p)
"#,
    );
    out
}

/// A C header: APIDs and service codes per telecommand, SPIDs, the raw
/// values of status texts, and where each TM parameter sits.
pub fn c_header(set: &MibSet, profile: &Profile, base: OffsetBase) -> String {
    let mut out = stamp(set, "//");
    out.push_str("#ifndef FENIX_MIB_H\n#define FENIX_MIB_H\n\n/* Telecommands: APID, service, subtype. */\n");
    for e in set.entries(Kind::Telecommand) {
        let r = &e.row;
        let n = ident(&e.name).to_uppercase();
        out.push_str(&format!("#define TC_{n}_APID {}\n#define TC_{n}_TYPE {}\n#define TC_{n}_SUBTYPE {}\n", r.clean("CCF_APID"), r.clean("CCF_TYPE"), r.clean("CCF_STYPE")));
    }
    out.push_str("\n/* TM packets: SPID. */\n");
    for e in set.entries(Kind::TmPacket) {
        let n = if e.alias.is_empty() { format!("SPID_{}", e.name) } else { ident(&e.alias).to_uppercase() };
        out.push_str(&format!("#define TM_{n} {}u\n", e.name));
    }
    out.push_str("\n/* Status texts: raw values. */\n");
    for (index, e) in set.entries(Kind::Calibration).iter().enumerate().filter(|(_, e)| matches!(e.cal, Some(CalKind::Status | CalKind::Text))) {
        let def = DefRef { kind: Kind::Calibration, index };
        if let CalBody::Texts(t) = detail::calibration(set, def) {
            out.push_str(&format!("enum {} {{ /* {} */\n", ident(&e.name), e.description.replace("*/", "")));
            for (raw, text) in t {
                if let Some(v) = parse_int(raw.split("..").next().unwrap_or(&raw)) {
                    out.push_str(&format!("    {}_{} = {v},\n", ident(&e.name).to_uppercase(), ident(&text).to_uppercase()));
                }
            }
            out.push_str("};\n");
        }
    }
    out.push_str("\n/* TM parameters: bit offset from the packet's start, and width in bits. */\n");
    for (i, e) in set.entries(Kind::TmPacket).iter().enumerate() {
        let spid = DefRef { kind: Kind::TmPacket, index: i };
        for p in placed(set, spid, profile, base) {
            out.push_str(&format!("#define TM_{}_{}_BIT {}\n#define TM_{}_{}_BITS {}\n", e.name, ident(&p.name).to_uppercase(), p.bit, e.name, ident(&p.name).to_uppercase(), p.bits));
        }
    }
    out.push_str("\n#endif /* FENIX_MIB_H */\n");
    out
}

/// A Python module: telecommands encoded to packets (with the project's
/// PUS-C or PUS-A header and CRC), TM packets decoded by SPID.
pub fn python(set: &MibSet, profile: &Profile, base: OffsetBase) -> String {
    let mut out = stamp(set, "#");
    let pus_c = profile.pus != fenix_ccsds::pus::PusEdition::A;
    out.push_str(&format!(
        r#""""Telecommands and TM packets from the MIB. encode(name, **args) -> bytes; decode(packet) -> (spid, {{param: raw}})."""

PUS_C = {}
SOURCE_ID = {src}


def _crc16(data):
    crc = 0xFFFF
    for b in data:
        crc ^= b << 8
        for _ in range(8):
            crc = ((crc << 1) ^ 0x1021) & 0xFFFF if crc & 0x8000 else (crc << 1) & 0xFFFF
    return crc


def _put(buf, at, n, value):
    for k in range(n):
        i = at + k
        bit = (value >> (n - 1 - k)) & 1
        while len(buf) <= i // 8:
            buf.append(0)
        if bit:
            buf[i // 8] |= 1 << (7 - i % 8)


def _get(data, at, n):
    v = 0
    for i in range(at, at + n):
        v = (v << 1) | ((data[i // 8] >> (7 - i % 8)) & 1)
    return v


# name -> (apid, service, subtype, ack, [(argument or None, bit, bits, fixed value, {{text: raw}})])
TELECOMMANDS = {{
"#,
        if pus_c { "True" } else { "False" },
        src = profile.tc_source_id
    ));
    for (i, e) in set.entries(Kind::Telecommand).iter().enumerate() {
        let tc = DefRef { kind: Kind::Telecommand, index: i };
        let r = &e.row;
        let els: Vec<String> = detail::tc_elements(set, tc)
            .into_iter()
            .filter_map(|el| {
                let (bit, bits) = (el.bit?, el.bits?);
                let texts = match el.cal.map(|c| detail::calibration(set, c)) {
                    Some(CalBody::Texts(t)) => t.iter().filter_map(|(raw, text)| Some(format!("{:?}: {}", text, parse_int(raw)?))).collect::<Vec<_>>().join(", "),
                    _ => String::new(),
                };
                let name = if el.fixed.is_some() || el.name.is_empty() { "None".to_string() } else { format!("{:?}", el.name) };
                Some(format!("({name}, {bit}, {bits}, {}, {{{texts}}})", el.fixed.as_deref().and_then(parse_int).unwrap_or(0)))
            })
            .collect();
        out.push_str(&format!(
            "    {:?}: ({}, {}, {}, {}, [{}]),\n",
            e.name,
            parse_int(r.clean("CCF_APID")).unwrap_or(0),
            parse_int(r.clean("CCF_TYPE")).unwrap_or(0),
            parse_int(r.clean("CCF_STYPE")).unwrap_or(0),
            parse_int(r.clean("CCF_ACK")).unwrap_or(9),
            els.join(", ")
        ));
    }
    out.push_str("}\n\n# (apid, service, subtype, [(bit, bits, value) checks of PI1/PI2], spid, [(parameter, bit from the packet's start, bits)])\nPACKETS = [\n");
    for (i, e) in set.entries(Kind::TmPacket).iter().enumerate() {
        let spid = DefRef { kind: Kind::TmPacket, index: i };
        let r = &e.row;
        let ps: Vec<String> = placed(set, spid, profile, base).into_iter().filter(|p| p.bits <= 64).map(|p| format!("({:?}, {}, {})", p.name, p.bit, p.bits)).collect();
        let pis: Vec<String> = pi_checks(set, r).iter().map(|(b, n, v)| format!("({b}, {n}, {v})")).collect();
        out.push_str(&format!(
            "    ({}, {}, {}, [{}], {:?}, [{}]),\n",
            parse_int(r.clean("PID_APID")).unwrap_or(0),
            parse_int(r.clean("PID_TYPE")).unwrap_or(0),
            parse_int(r.clean("PID_STYPE")).unwrap_or(0),
            pis.join(", "),
            e.name,
            ps.join(", ")
        ));
    }
    out.push_str(
        r#"]


def encode(name, seq=0, **args):
    apid, service, subtype, ack, elements = TELECOMMANDS[name]
    app = bytearray()
    for arg, bit, bits, fixed, texts in elements:
        value = fixed if arg is None else args[arg]
        if isinstance(value, str):
            value = texts[value] if value in texts else int(value, 0)
        _put(app, bit, bits, int(value))
    if PUS_C:
        head = bytes([0x20 | (ack & 0xF), service, subtype, SOURCE_ID >> 8, SOURCE_ID & 0xFF])
    else:
        head = bytes([0x10 | (ack & 0xF), service, subtype])
    data = head + bytes(app)
    length = len(data) + 2 - 1
    pkt = bytes([0x18 | (apid >> 8), apid & 0xFF, 0xC0 | (seq >> 8), seq & 0xFF, length >> 8, length & 0xFF]) + data
    crc = _crc16(pkt)
    return pkt + bytes([crc >> 8, crc & 0xFF])


def decode(packet):
    apid = ((packet[0] << 8) | packet[1]) & 0x7FF
    service, subtype = packet[7], packet[8]
    for a, s, t, checks, spid, params in PACKETS:
        if (a, s, t) == (apid, service, subtype) and all(b + n <= len(packet) * 8 and _get(packet, b, n) == v for b, n, v in checks):
            break
    else:
        return None, {}
    return spid, {p: _get(packet, bit, bits) for p, bit, bits in params if bit + bits <= len(packet) * 8}
"#,
    );
    out
}

/// An ICD in Markdown: every telecommand with its parameters, every
/// packet with its layout.
pub fn icd(set: &MibSet, profile: &Profile, base: OffsetBase) -> String {
    let mut out = format!("# Interface control: telecommands and telemetry\n\n_{}_\n", stamp(set, "").trim());
    out.push_str("\n## Telecommands\n");
    for (i, e) in set.entries(Kind::Telecommand).iter().enumerate() {
        let tc = DefRef { kind: Kind::Telecommand, index: i };
        let r = &e.row;
        out.push_str(&format!("\n### {} -- {}\n\nPUS {},{} · APID {} · {}\n\n", e.name, e.description, r.clean("CCF_TYPE"), r.clean("CCF_STYPE"), types::apid(r.clean("CCF_APID"), true), r.clean("CCF_SUBSYS")));
        out.push_str("| Parameter | Bits | Type | Value | Description |\n|---|---|---|---|---|\n");
        for el in detail::tc_elements(set, tc) {
            let bits = match (el.bit, el.bits) {
                (Some(b), Some(n)) => format!("{b}+{n}"),
                _ => String::new(),
            };
            let value = match &el.fixed {
                Some(v) => format!("fixed {v}"),
                None => el.allowed.clone(),
            };
            out.push_str(&format!("| {} | {bits} | {} | {} | {} |\n", if el.name.is_empty() { "spare" } else { &el.name }, el.type_name, value.replace('|', "/"), el.description.replace('|', "/")));
        }
    }
    out.push_str("\n## Telemetry packets\n");
    for (i, e) in set.entries(Kind::TmPacket).iter().enumerate() {
        let spid = DefRef { kind: Kind::TmPacket, index: i };
        let r = &e.row;
        out.push_str(&format!("\n### SPID {} {} -- {}\n\nPUS {},{} · APID {}\n\n", e.name, e.alias, e.description, r.clean("PID_TYPE"), r.clean("PID_STYPE"), types::apid(r.clean("PID_APID"), true)));
        out.push_str("| Octet.bit | Parameter | Bits | Description |\n|---|---|---|---|\n");
        for p in placed(set, spid, profile, base) {
            let d = set.resolve(&p.name).map(|d| set.get(d).description.clone()).unwrap_or_default();
            out.push_str(&format!("| {}.{} | {} | {} | {} |\n", p.bit / 8, p.bit % 8, p.name, p.bits, d.replace('|', "/")));
        }
    }
    out
}

/// Every telecommand with its defaults (status texts' first value where
/// there's no default), as the hex of its packet -- or why it couldn't
/// be built.
pub fn vectors(set: &MibSet, profile: &Profile) -> String {
    let mut out = stamp(set, "#");
    for (i, e) in set.entries(Kind::Telecommand).iter().enumerate() {
        let tc = DefRef { kind: Kind::Telecommand, index: i };
        let args: Vec<(String, String)> = crate::telecommand::tc_parameters(set.index(), &e.row)
            .into_iter()
            .filter(|p| !p.fixed && !p.name.is_empty())
            .map(|p| {
                let d = crate::telecommand::parameter_domain(set.index(), &p);
                let v = if !d.default.is_empty() { d.default } else if let Some(a) = d.aliases.first() { a.clone() } else if let Some((lo, _)) = d.ranges.first() { format!("{lo}") } else { "0".into() };
                (p.name, v)
            })
            .collect();
        match packets::encode_tc(set, tc, &args, profile, 0) {
            Ok(p) => out.push_str(&format!("{:<12} {}\n", e.name, fenix_ccsds::field::hex(&p.bytes))),
            Err(why) => out.push_str(&format!("{:<12} # {why}\n", e.name)),
        }
    }
    out
}

/// The file generator `kind` makes.
pub fn generate(kind: &str, set: &MibSet, profile: &Profile, base: OffsetBase) -> Option<String> {
    Some(match kind {
        "xtce" => xtce(set, profile, base),
        "wireshark" => wireshark(set, profile, base),
        "c" => c_header(set, profile, base),
        "python" => python(set, profile, base),
        "icd" => icd(set, profile, base),
        "vectors" => vectors(set, profile),
        _ => return None,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::set::tests::fixture;

    #[test]
    fn every_generator_writes_what_it_says() {
        let root = fixture();
        let set = MibSet::load(vec![root.clone()], None);
        let p = Profile::default();
        let b = OffsetBase::AfterHeaders;
        let x = generate("xtce", &set, &p, b).unwrap();
        assert!(roxmltree::Document::parse(&x).is_ok(), "well-formed XML");
        assert!(x.contains("<xtce:MetaCommand name=\"ZTC08101\"") && x.contains("<xtce:Enumeration value=\"2\" label=\"AUTO\"/>"));
        let lua = generate("wireshark", &set, &p, b).unwrap();
        assert!(lua.contains("{ 1010, 3, 25, {") && lua.contains("\"30211 TCS_HK_FAST\"") && lua.contains("DissectorTable.get(\"udp.port\")"), "{lua}");
        let c = generate("c", &set, &p, b).unwrap();
        assert!(c.contains("#define TC_ZTC08101_APID 1010") && c.contains("PAF00042_AUTO = 2,") && c.contains("#define TM_TCS_HK_FAST 30211u"), "{c}");
        let py = generate("python", &set, &p, b).unwrap();
        assert!(py.contains("\"ZTC08101\": (1010, 8, 1,") && py.contains("def encode(name, seq=0, **args):") && py.contains("PUS_C = True\n"));
        run_python(&generate("python", &crate::packets::tests::mission(), &p, b).unwrap());
        let icd = generate("icd", &set, &p, b).unwrap();
        assert!(icd.contains("### ZTC08101 -- Set heater control mode") && icd.contains("| PTH00102 | 16+8 | enum8 | OFF ON AUTO |"), "{icd}");
        let v = generate("vectors", &set, &p, b).unwrap();
        assert!(v.lines().any(|l| l.starts_with("ZTC08101")), "{v}");
        assert!(generate("nope", &set, &p, b).is_none());
        std::fs::remove_dir_all(&root.path).ok();
    }

    /// Runs the generated module, when Python is installed: its encode
    /// gives the bytes `packets::encode_tc` does, and its decode reads the
    /// parameters back out of a TM packet.
    fn run_python(module: &str) {
        let dir = std::env::temp_dir().join(format!("fenix-mib-python-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("mib.py"), module).unwrap();
        let script = "import mib\n\
            print(mib.encode('ZTC08101', seq=7, PTH00101=3, PTH00102='AUTO').hex())\n\
            spid, params = mib.decode(bytes.fromhex('0bf2c1230016200319002300008 14b878a80000001010bb80a28023401'.replace(' ', '')))\n\
            print(spid, params['NTH00123'], params['NTH00124'])\n\
            print(mib.decode(bytes.fromhex('0bf2c123001620031900230000814b878a80000002010bb80a28023401'))[0])\n";
        let Ok(out) = std::process::Command::new("python").arg("-c").arg(script).current_dir(&dir).output() else { return };
        if !out.status.success() && String::from_utf8_lossy(&out.stderr).contains("not found") {
            return; // the Windows Store stub, not a Python
        }
        let text = String::from_utf8_lossy(&out.stdout);
        assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
        assert_eq!(text.lines().collect::<Vec<_>>(), ["1bf2c007000929080100000c03023fa3", "30211 3000 2600", "None"]);
    }
}
