# Usage: pip install fonttools; download MartianMono[wdth,wght].ttf from
# github.com/google/fonts (ofl/martianmono) as MartianMono.ttf, then
#   python outline.py > ../src/wordmark.rs
"""One-off: turn "fenix" set in Martian Mono SemiBold (tracking -4%) into
flattened outline contours, emitted as Rust source for fenix-brand."""
import sys
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont
from fontTools.pens.basePen import BasePen

WORD = "fenix"
TRACKING = -0.04   # of the em
STEPS = 12         # line segments per quadratic curve

font = instantiateVariableFont(TTFont("MartianMono.ttf"), {"wght": 600, "wdth": 100})
upm = font["head"].unitsPerEm
cap = font["OS/2"].sCapHeight
xh = font["OS/2"].sxHeight
cmap = font.getBestCmap()
gs = font.getGlyphSet()
hmtx = font["hmtx"]


class Flatten(BasePen):
    def __init__(self, glyphset, dx):
        super().__init__(glyphset)
        self.dx = dx
        self.contours = []
        self.cur = None

    def _pt(self, p):
        # em units, y down, baseline at 0
        return ((p[0] + self.dx) / upm, -p[1] / upm)

    def _moveTo(self, p):
        self.cur = [self._pt(p)]
        self._last = p

    def _lineTo(self, p):
        self.cur.append(self._pt(p))
        self._last = p

    def _qCurveToOne(self, p1, p2):
        p0 = self._last
        for i in range(1, STEPS + 1):
            t = i / STEPS
            x = (1 - t) ** 2 * p0[0] + 2 * (1 - t) * t * p1[0] + t * t * p2[0]
            y = (1 - t) ** 2 * p0[1] + 2 * (1 - t) * t * p1[1] + t * t * p2[1]
            self.cur.append(self._pt((x, y)))
        self._last = p2

    def _curveToOne(self, p1, p2, p3):
        p0 = self._last
        for i in range(1, STEPS + 1):
            t = i / STEPS
            mt = 1 - t
            x = mt**3 * p0[0] + 3 * mt * mt * t * p1[0] + 3 * mt * t * t * p2[0] + t**3 * p3[0]
            y = mt**3 * p0[1] + 3 * mt * mt * t * p1[1] + 3 * mt * t * t * p2[1] + t**3 * p3[1]
            self.cur.append(self._pt((x, y)))
        self._last = p3

    def _closePath(self):
        if self.cur:
            self.contours.append(self.cur)
        self.cur = None

    _endPath = _closePath


contours = []
x = 0
for ch in WORD:
    name = cmap[ord(ch)]
    pen = Flatten(gs, x)
    gs[name].draw(pen)
    contours.extend(pen.contours)
    x += hmtx[name][0] + TRACKING * upm
advance = (x - TRACKING * upm) / upm

xs = [p[0] for c in contours for p in c]
ys = [p[1] for c in contours for p in c]
out = sys.stdout
out.write("// Generated by fenix-brand's outline step from Martian Mono SemiBold\n")
out.write("// (SIL Open Font License 1.1, see LICENSE-martian-mono.txt): the word\n")
out.write('// "fenix" at tracking -4%, as flattened contours in em units, y down,\n')
out.write("// baseline at 0. Regenerate only if the wordmark itself changes.\n\n")
out.write(f"pub const CAP_HEIGHT: f32 = {cap / upm:.5};\n")
out.write(f"pub const X_HEIGHT: f32 = {xh / upm:.5};\n")
out.write(f"pub const ADVANCE: f32 = {advance:.5};\n")
out.write(f"pub const MIN_X: f32 = {min(xs):.5};\n")
out.write(f"pub const MAX_X: f32 = {max(xs):.5};\n")
out.write(f"pub const MIN_Y: f32 = {min(ys):.5};\n")
out.write(f"pub const MAX_Y: f32 = {max(ys):.5};\n\n")
out.write("pub const CONTOURS: &[&[(f32, f32)]] = &[\n")
for c in contours:
    pts = ", ".join(f"({px:.4}, {py:.4})" for px, py in c)
    out.write(f"    &[{pts}],\n")
out.write("];\n")
