[package]
name = "fenix-config"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
fenix-storage = { path = "../fenix-storage" }
dirs = "6"
serde = { version = "1", features = ["derive"] }
toml_edit = "0.22"

